### PR TITLE
Backport: Update o-editorial-typography h4 for a "features xhead" heading

### PR DESCRIPTION
**Pull request by notlee**
See: https://github.com/Financial-Times/origami/pull/324

### CODE REVIEW

**Review by chee — APPROVED** [review]

**Comment by notlee** [comment]
yikes, this has the wrong base

**Comment by origamiserviceuser** [comment]
o-editorial-typography bundle size difference from 2.0.2 to 7e4d270e47e467fdbbf4a1fbb3034f264b214879
No bundle size differences found.

**Comment by origamiserviceuser** [comment]
We tried to version this automatically but we failed. Please view the errors at https://github.com/Financial-Times/o-editorial-typography/runs/1307522089?check_suite_focus=true

**Comment by origamiserviceuser** [comment]
We tried to version this automatically but we failed. Please view the errors at https://github.com/Financial-Times/o-editorial-typography/runs/1307522089?check_suite_focus=true

**Pull request merged**
