### PR TITLE
Remove border as well as text-decoration from tags when used as links

### PR DESCRIPTION
**Pull request by i-like-robots**
Before:

Screenshot 2020-01-15 at 13 35 56

After:

Screenshot 2020-01-15 at 13 36 09

### CODE REVIEW

**Review by notlee — APPROVED** [review]
thank you 👍

**Comment by notlee** [comment]
I'll update those failing Sass tests.

**Comment by origamiserviceuser** [comment]
o-editorial-typography bundle size difference from 1.0.2 to 260fc994f2cb6312cc82421b820beacee4c575d1
No significant bundle size differences found.

**Comment by i-like-robots** [comment]
🙇

**Pull request merged**
